name: drought-indicators
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.14
  - cffi=1.15.1
  - cftime=1.6.2
  - curl=7.83.1
  - dbus=1.13.6
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.0.0
  - expat=2.4.9
  - flit-core=3.7.1
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=69.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.3
  - ipython=8.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - krb5=1.19.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=3.0.0
  - libgfortran5=11.3.0
  - libglib=2.72.1
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libpq=14.5
  - libsodium=1.0.18
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.9.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lxml=4.8.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - nbclient=0.6.8
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.6.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.1
  - notebook=6.4.12
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.3
  - openssl=3.0.5
  - packaging=21.3
  - pandas=1.5.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.31
  - prompt_toolkit=3.0.31
  - psutil=5.9.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyrsistent=0.18.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.8
  - pytz=2022.2.1
  - pyzmq=24.0.1
  - qt=5.12.9
  - qtconsole=5.3.2
  - qtconsole-base=5.3.2
  - qtpy=2.2.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=65.3.0
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.3
  - stack_data=0.5.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.4.0
  - typing_extensions=4.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - xarray=2022.6.0
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cdsapi==0.5.1
    - certifi==2022.6.15.2
    - charset-normalizer==2.1.1
    - idna==3.4
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - requests==2.28.1
    - tqdm==4.64.1
    - urllib3==1.26.12
